[package]
name = "vxapo-driver"
version = "0.1.0"
edition = "2021"
description = "VxAPO audio processing driver (Windows APO DLL)"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
log = "0.4"
once_cell = "1"
rustfft = "6.4.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "0.8"

[dependencies.windows]
version = "=0.62.2"
features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_Media_Audio_Apo",
    "Win32_Media_KernelStreaming",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Variant",
    "Win32_System_Com_StructuredStorage",
    "Win32_Storage_FileSystem",
]
default-features = false

[dependencies.windows-core]
version = "=0.62.2"

[dependencies.windows-implement]
version = "=0.60.2"

[dependencies.windows-interface]
version = "=0.59.3"


[features]
default = []
aec = []

[profile.release]
panic = "abort"
codegen-units = 1
lto = true

[profile.dev]
panic = "unwind"
